# Generated by Django 4.0 on 2021-12-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaurante',
            new_name='Restaurant',
        ),
    ]
