# Generated by Django 4.0 on 2021-12-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_restaurant_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='tipoCocina',
            field=models.CharField(max_length=100),
        ),
    ]
