# Generated by Django 4.0 on 2021-12-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_restaurant_tipococina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='precioMedio',
            field=models.FloatField(null=True),
        ),
    ]
