# Generated by Django 4.0 on 2021-12-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_restaurant_preciomedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='puntuacion',
            field=models.FloatField(null=True),
        ),
    ]
