# Generated by Django 4.0 on 2021-12-28 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_restaurant_puntuacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='informacion',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='caracteristicas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.caracteristica'),
        ),
    ]
