# Generated by Django 4.0 on 2021-12-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_caracteristica_alter_restaurant_informacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='caracteristicas',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
