# Generated by Django 4.0 on 2021-12-28 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_restaurant_caracteristicas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caracteristica',
        ),
    ]
