# Generated by Django 4.0 on 2021-12-29 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_caracteristica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='direccion',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
