# Generated by Django 4.0 on 2021-12-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_user_remove_restaurant_id_alter_restaurant_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='horarioDomingo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='horarioJueves',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='horarioLunes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='horarioMartes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='horarioMiercoles',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='horarioSabado',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='horarioViernes',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='informacion',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='tipoCocina',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
