# Generated by Django 4.0 on 2022-01-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_restaurant_horariodomingo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='caracteristicas',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='informacion',
            field=models.TextField(null=True),
        ),
    ]
